-- MySQL Script generated by MySQL Workbench
-- Sun Aug 13 16:44:27 2017
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema db_shift
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema db_shift
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `db_shift` DEFAULT CHARACTER SET utf8 ;
USE `db_shift` ;

-- -----------------------------------------------------
-- Table `db_shift`.`tb_usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_shift`.`tb_usuario` (
  `id_user` INT NOT NULL AUTO_INCREMENT,
  `nm_user` VARCHAR(45) NOT NULL,
  `pass_user` VARCHAR(45) NOT NULL,
  `login_user` VARCHAR(45) NOT NULL,
  `data_registro_user` DATETIME NULL,
  `email_user` VARCHAR(80) NOT NULL,
  `nick_user` VARCHAR(45) NOT NULL,
  `data_nascimento_user` DATE NOT NULL,
  `sexo_user` VARCHAR(25) NULL,
  PRIMARY KEY (`id_user`))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
