-- MySQL Script generated by MySQL Workbench
-- Mon Aug 21 02:03:41 2017
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema db_shift
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema db_shift
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `db_shift` DEFAULT CHARACTER SET utf8 ;
USE `db_shift` ;

-- -----------------------------------------------------
-- Table `db_shift`.`tb_roles`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_shift`.`tb_roles` (
  `id_roles` INT NOT NULL AUTO_INCREMENT,
  `role` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id_roles`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_shift`.`tb_artigos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_shift`.`tb_artigos` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `user_id` INT NOT NULL,
  `titulo` VARCHAR(45) NOT NULL,
  `conteudo` MEDIUMTEXT NOT NULL,
  `view` INT NULL,
  `banner` VARCHAR(75) NULL DEFAULT 'assets/imgs/jinx.jpg',
  PRIMARY KEY (`id`),
  INDEX `artigos_user_id_idx` (`user_id` ASC),
  CONSTRAINT `artigos_user_id`
    FOREIGN KEY (`user_id`)
    REFERENCES `db_shift`.`tb_users` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_shift`.`tb_users`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_shift`.`tb_users` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nm_user` VARCHAR(45) NOT NULL,
  `pass_user` VARCHAR(45) NOT NULL,
  `login_user` VARCHAR(45) NOT NULL,
  `email_user` VARCHAR(80) NOT NULL,
  `data_nascimento_user` DATE NULL,
  `role_id` INT NULL DEFAULT 2,
  `status_user` INT(1) NULL DEFAULT 1,
  `data_registro_user` DATETIME NULL,
  `sexo_user` VARCHAR(25) NULL,
  `artigo_id` INT NULL,
  PRIMARY KEY (`id`),
  INDEX `users_role_id_idx` (`role_id` ASC),
  INDEX `users_artigo_id_idx` (`artigo_id` ASC),
  CONSTRAINT `users_role_id`
    FOREIGN KEY (`role_id`)
    REFERENCES `db_shift`.`tb_roles` (`id_roles`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `users_artigo_id`
    FOREIGN KEY (`artigo_id`)
    REFERENCES `db_shift`.`tb_artigos` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_shift`.`tb_login_attempts`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_shift`.`tb_login_attempts` (
  `id_attempts` INT NOT NULL AUTO_INCREMENT,
  `user_id` INT NOT NULL,
  `created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id_attempts`),
  INDEX `login_attempts_id_user_idx` (`user_id` ASC),
  CONSTRAINT `login_attempts_id_user`
    FOREIGN KEY (`user_id`)
    REFERENCES `db_shift`.`tb_users` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_shift`.`tb_recoveries`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_shift`.`tb_recoveries` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `user_id` INT NOT NULL,
  `token` VARCHAR(255) NOT NULL,
  `status` INT(1) NOT NULL DEFAULT 0,
  PRIMARY KEY (`id`),
  INDEX `passwords_user_id_idx` (`user_id` ASC),
  CONSTRAINT `recoveries_user_id`
    FOREIGN KEY (`user_id`)
    REFERENCES `db_shift`.`tb_users` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
