-- MySQL Script generated by MySQL Workbench
-- Thu Aug 24 18:16:11 2017
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema db_shift
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema db_shift
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `db_shift` DEFAULT CHARACTER SET utf8 ;
USE `db_shift` ;

-- -----------------------------------------------------
-- Table `db_shift`.`tb_users`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_shift`.`tb_users` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nm_user` VARCHAR(45) NOT NULL,
  `pass_user` VARCHAR(45) NOT NULL,
  `login_user` VARCHAR(45) NOT NULL,
  `email_user` VARCHAR(80) NOT NULL,
  `data_nascimento_user` DATE NULL,
  `status_user` INT(1) NULL DEFAULT 1,
  `data_registro_user` DATETIME NULL,
  `sexo_user` VARCHAR(25) NULL,
  `avatar_user` VARCHAR(145) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_shift`.`tb_login_attempts`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_shift`.`tb_login_attempts` (
  `id_attempts` INT NOT NULL AUTO_INCREMENT,
  `user_id` INT NOT NULL,
  `created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id_attempts`),
  INDEX `login_attempts_id_user_idx` (`user_id` ASC),
  CONSTRAINT `login_attempts_id_user`
    FOREIGN KEY (`user_id`)
    REFERENCES `db_shift`.`tb_users` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_shift`.`tb_recoveries`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_shift`.`tb_recoveries` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `user_id` INT NOT NULL,
  `token` VARCHAR(255) NOT NULL,
  `status` INT(1) NOT NULL DEFAULT 0,
  PRIMARY KEY (`id`),
  INDEX `passwords_user_id_idx` (`user_id` ASC),
  CONSTRAINT `recoveries_user_id`
    FOREIGN KEY (`user_id`)
    REFERENCES `db_shift`.`tb_users` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_shift`.`tb_admins`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_shift`.`tb_admins` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nm_admin` VARCHAR(45) NOT NULL,
  `pass_admin` VARCHAR(100) NOT NULL,
  `login_admin` VARCHAR(45) NOT NULL,
  `email_admin` VARCHAR(45) NOT NULL,
  `status_admin` BINARY(1) NULL,
  `artigo_id` INT NULL,
  `avatar_admin` VARCHAR(150) NULL DEFAULT 'avatar/1.jpg',
  PRIMARY KEY (`id`),
  INDEX `admins_artigo_id_idx` (`artigo_id` ASC),
  CONSTRAINT `admins_artigo_id`
    FOREIGN KEY (`artigo_id`)
    REFERENCES `db_shift`.`tb_artigos` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_shift`.`tb_artigos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_shift`.`tb_artigos` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `autor_id` INT NOT NULL,
  `titulo` VARCHAR(45) NOT NULL,
  `conteudo` MEDIUMTEXT NOT NULL,
  `view` INT NULL,
  `banner` VARCHAR(124) NULL DEFAULT 'artigos/banners/jinx.jpg',
  PRIMARY KEY (`id`),
  INDEX `artigos_autor_id_idx` (`autor_id` ASC),
  CONSTRAINT `artigos_autor_id`
    FOREIGN KEY (`autor_id`)
    REFERENCES `db_shift`.`tb_admins` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
